import { Post } from "./types";

export const samplePostData: Post[] = [
  {
    userId: "user1",
    postId: "post1",
    createdAt: "2025-04-01T10:00:00Z",
    userAvatar: "https://res.cloudinary.com/dwv76nhoy/image/upload/v1739337151/rrspasosi59xmsriilae.png",
    userDisplayName: "Tâm An",
    userName: "healing_soul",
    postType: "VIDEO",
    videoUrl: "https://res.cloudinary.com/dwv76nhoy/video/upload/v1740748142/videos/ku2ammahemr2k4iiezza.mp4",
    imageUrls: [],
    title: "Lorem ipsum dolor sit amet",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque euismod, nisi eu consectetur cursus, nisl nunc.",
    tags: ["healing", "mentalhealth", "inspiration"],
    likeCount: "120",
    commentCount: "15",
    playlistCount: "5",
    audioUrl: "",
    audioOwnerAvatar: "https://res.cloudinary.com/dwv76nhoy/image/upload/v1739337151/rrspasosi59xmsriilae.png",
    audioOwnerName: "Calm Studio",
    audioId: "audio1",
    comments: [
      {
        commentId: "cmt1",
        userAvatar: "https://res.cloudinary.com/dwv76nhoy/image/upload/v1739337151/rrspasosi59xmsriilae.png",
        content: "Video rất ý nghĩa!",
        displayName: "Lan Chi",
        createdAt: "2025-04-01T10:05:00Z",
        replies: [
          {
            commentId: "reply1",
            userAvatar: "https://res.cloudinary.com/dwv76nhoy/image/upload/v1739337151/rrspasosi59xmsriilae.png",
            content: "Cảm ơn bạn nhiều!",
            displayName: "Tâm An",
            createdAt: "2025-04-01T10:06:00Z",
          },
        ],
      },
    ],
  },
  {
    userId: "user2",
    postId: "post2",
    createdAt: "2025-04-02T15:00:00Z",
    userAvatar: "https://res.cloudinary.com/dwv76nhoy/image/upload/v1739337151/rrspasosi59xmsriilae.png",
    userDisplayName: "Minh Triết",
    userName: "growth_mindset",
    postType: "IMG",
    videoUrl: "",
    imageUrls: [
      "https://res.cloudinary.com/dwv76nhoy/image/upload/v1739337151/images/sikxb1qmpocwuwpbgapc",
      "https://res.cloudinary.com/dwv76nhoy/image/upload/c_crop,g_auto,w_1080/v1739337151/rrspasosi59xmsriilae.png",
      "https://res.cloudinary.com/dwv76nhoy/image/upload/c_crop,g_auto,w_1080/v1739337151/images/sikxb1qmpocwuwpbgapc",
    ],
    title: "Lorem ipsum dolor sit amet",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque habitant morbi tristique senectus et netus.",
    tags: ["selfgrowth", "dailyquotes", "photojournal"],
    likeCount: "85",
    commentCount: "10",
    playlistCount: "3",
    audioUrl: "https://res.cloudinary.com/dwv76nhoy/video/upload/v1741011150/audios/t0m4l8rgcrrtbdbxnanp.mp3",
    audioOwnerAvatar: "https://res.cloudinary.com/dwv76nhoy/image/upload/v1739337151/rrspasosi59xmsriilae.png",
    audioOwnerName: "Music Maker",
    audioId: "audio2",
    comments: [
      {
        commentId: "cmt2",
        userAvatar: "https://res.cloudinary.com/dwv76nhoy/image/upload/v1739337151/rrspasosi59xmsriilae.png",
        content: "Ảnh truyền cảm hứng quá!",
        displayName: "Alex Brown",
        createdAt: "2025-04-02T15:10:00Z",
        replies: [],
      },
    ],
  },
  {
    userId: "user3",
    postId: "post3",
    createdAt: "2025-04-03T08:00:00Z",
    userAvatar: "https://res.cloudinary.com/dwv76nhoy/image/upload/v1739337151/rrspasosi59xmsriilae.png",
    userDisplayName: "Sức Khỏe",
    userName: "healthy_habits",
    postType: "VIDEO",
    videoUrl: "https://res.cloudinary.com/dwv76nhoy/video/upload/v1740748437/videos/wnz7qmx8ioch6e3zvylv.mp4",
    imageUrls: [],
    title: "Lorem ipsum dolor sit amet",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    tags: ["health", "routine", "fitness"],
    likeCount: "95",
    commentCount: "8",
    playlistCount: "2",
    audioUrl: "",
    audioOwnerAvatar: "https://res.cloudinary.com/dwv76nhoy/image/upload/v1739337151/rrspasosi59xmsriilae.png",
    audioOwnerName: "LifeCoach",
    audioId: "audio3",
    comments: [],
  },
  {
    userId: "user4",
    postId: "post4",
    createdAt: "2025-04-04T13:00:00Z",
    userAvatar: "https://res.cloudinary.com/dwv76nhoy/image/upload/v1739337151/rrspasosi59xmsriilae.png",
    userDisplayName: "Thiên Ân",
    userName: "tienan.vn",
    postType: "VIDEO",
    videoUrl: "https://res.cloudinary.com/dwv76nhoy/video/upload/v1740670978/videos/jjot1n9nnbpkxuin2gcv.mp4",
    imageUrls: [],
    title: "Lorem ipsum dolor sit amet",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
    tags: ["lofi", "chill", "weekendvibes"],
    likeCount: "132",
    commentCount: "21",
    playlistCount: "4",
    audioUrl: "",
    audioOwnerAvatar: "https://res.cloudinary.com/dwv76nhoy/image/upload/v1739337151/rrspasosi59xmsriilae.png",
    audioOwnerName: "Chill Studio",
    audioId: "audio4",
    comments: [],
  },
  {
    userId: "user5",
    postId: "post5",
    createdAt: "2025-04-05T18:30:00Z",
    userAvatar: "https://res.cloudinary.com/dwv76nhoy/image/upload/v1739337151/rrspasosi59xmsriilae.png",
    userDisplayName: "Ngọc Minh",
    userName: "ngoc.minh.music",
    postType: "VIDEO",
    videoUrl: "https://res.cloudinary.com/dwv76nhoy/video/upload/v1740748142/videos/ku2ammahemr2k4iiezza.mp4",
    imageUrls: [],
    title: "Lorem ipsum dolor sit amet",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacinia odio vitae vestibulum vestibulum.",
    tags: ["cover", "music", "vietpop"],
    likeCount: "200",
    commentCount: "32",
    playlistCount: "6",
    audioUrl: "",
    audioOwnerAvatar: "https://res.cloudinary.com/dwv76nhoy/image/upload/v1739337151/rrspasosi59xmsriilae.png",
    audioOwnerName: "Ngọc Minh",
    audioId: "audio5",
    comments: [],
  },
];
